#!/usr/bin/env python3
"""
Send CPL Daily Report to Feishu via Webhook
Reads cpl_summary.json, builds a rich card message, sends via Feishu Bot webhook.
"""
import json, os, sys, requests

ROOT = os.environ.get('GITHUB_WORKSPACE', os.path.dirname(os.path.abspath(__file__)))
WEBHOOK_URL = os.environ.get('FEISHU_WEBHOOK_URL', '')
REPORT_URL = os.environ.get('REPORT_URL', '')  # GitHub Pages URL

if not WEBHOOK_URL:
    print("ERROR: FEISHU_WEBHOOK_URL not set!")
    sys.exit(1)

with open(f'{ROOT}/cpl_summary.json') as f:
    s = json.load(f)

# ── Format helpers ──
def fmt_dollar(v):
    return f"${v:,.2f}" if v else "$0"

def fmt_pct_str(v):
    if v is None: return "N/A"
    return f"{v:+.1f}%"

def fmt_rank(items, n=3, fmt_fn=None):
    lines = []
    for i, e in enumerate(items[:n]):
        if fmt_fn:
            lines.append(f"{i+1}. {fmt_fn(e)}")
    return "\n".join(lines)

# Build report URL
report_url = REPORT_URL
if not report_url:
    repo = os.environ.get('GITHUB_REPOSITORY', 'kkfwq/cpl-daily')
    report_url = f"https://kkfwq.github.io/cpl-daily/report.html"

# ── Build message ──
ext_top3 = fmt_rank(s.get('ext_top10', []), 3,
    lambda e: f"**{e['name'][:25]}** — ${e['rev']:,.2f} (GP ${e['gp']:,.2f}, CR {e['cr']:.2f}%)")

adv_top3 = fmt_rank(s.get('adv_top10', []), 3,
    lambda e: f"**{e['name'][:25]}** — ${e['rev']:,.2f} (GP ${e['gp']:,.2f}, Margin {e['margin']:.1f}%)")

# Feishu interactive card
card = {
    "msg_type": "interactive",
    "card": {
        "header": {
            "title": {"tag": "plain_text", "content": f"📊 CPL Daily - {s['main_display']}"},
            "template": "blue"
        },
        "elements": [
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": f"**Revenue:** ${s['revenue']:,.2f}  |  **GP:** ${s['gp']:,.2f} ({s['margin']}%)  |  **Conv:** {s['conversions']:,}"}
            },
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": f"**DoD:** Rev {fmt_pct_str(s.get('dod_rev'))} | GP {fmt_pct_str(s.get('dod_gp'))} | Conv {fmt_pct_str(s.get('dod_conv'))}"}
            },
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": f"**WoW:** Rev {fmt_pct_str(s.get('wow_rev'))} | GP {fmt_pct_str(s.get('wow_gp'))}"}
            },
            {"tag": "hr"},
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": f"🔥 **External Top 3** ({s.get('ext_count', 0)} total)\n{ext_top3}"}
            },
            {"tag": "hr"},
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": f"💰 **Advertiser Top 3**\n{adv_top3}"}
            },
            {"tag": "hr"},
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": f"📅 **MTD** ({s.get('mtd_days', '?')} days): Rev **${s['mtd_rev']:,.2f}** | GP **${s['mtd_gp']:,.2f}** | Conv **{s['mtd_conv']:,}**"}
            },
            {"tag": "hr"},
            {
                "tag": "action",
                "actions": [
                    {
                        "tag": "button",
                        "text": {"tag": "plain_text", "content": "📊 View Full Report"},
                        "type": "primary",
                        "url": report_url
                    }
                ]
            },
            {
                "tag": "note",
                "elements": [{"tag": "plain_text", "content": f"🤖 Auto-generated by GitHub Actions | {s['main_date']}"}]
            }
        ]
    }
}

# Send
r = requests.post(WEBHOOK_URL, json=card, timeout=15)
print(f"Feishu response: {r.status_code} {r.text[:300]}")
if r.status_code == 200 and r.json().get('StatusCode') == 0:
    print("Feishu message sent successfully!")
else:
    print(f"Feishu send failed: {r.text}")
    sys.exit(1)
